# Generated by Django 4.0 on 2021-12-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_booktable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktable',
            name='First_Name',
        ),
        migrations.RemoveField(
            model_name='booktable',
            name='phone',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
