# Generated by Django 4.0 on 2021-12-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_booktable_email_alter_booktable_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktable',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='date_time',
            field=models.DateTimeField(verbose_name='book table date'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/customer/'),
        ),
    ]
