# Generated by Django 4.0 on 2021-12-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_booktable_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='date_time',
            field=models.DateField(verbose_name='book table date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='table_no',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=30),
        ),
    ]
