# Generated by Django 4.0 on 2021-12-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_booktable_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='date_time',
            field=models.DateTimeField(verbose_name='book table date'),
        ),
    ]
