# Generated by Django 4.0 on 2021-12-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_booktable_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktable',
            name='timeBook',
            field=models.CharField(choices=[('11.00 - 11.45', '11.00 - 11.45'), ('12.00 - 13.45', '12.00 - 13.45'), ('13.00 - 13.45', '13.00 - 13.45'), ('14.00 - 14.45', '14.00 - 14.45'), ('15.00 - 15.45', '15.00 - 15.45'), ('16.00 - 16.45', '16.00 - 16.45'), ('17.00 - 17.45', '17.00 - 17.45'), ('18.00 - 18.45', '18.00 - 18.45'), ('19.00 - 19.45', '19.00 - 19.45'), ('20.00 - 20.45', '20.00 - 20.45'), ('21.00 - 21.45', '21.00 - 21.45'), ('22.00 - 22.45', '22.00 - 22.45')], default=7, max_length=30),
            preserve_default=False,
        ),
    ]
